version: '3'

services:
  zerotier:
    build: .
    environment:
      - NETWORK_ID=9b............34
#      - ROUTES=10.10.12.0/23,10.147.20.115;10.10.14.0/23,10.147.20.220
    volumes:
      - './config/route.list:/config/route.list:ro'
      - /var/lib/zerotier-one:/var/lib/zerotier-one
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    network_mode: host
    devices: 
      - /dev/net/tun
    privileged: true
    restart: always